version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - webnet
    restart: unless-stopped

  app1:
    build: ./app1
    environment:
      - PORT=3000
    expose:
      - "3000"
    networks:
      - webnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  app2:
    build: ./app2
    environment:
      - PORT=8000
    expose:
      - "8000"
    networks:
      - webnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  app3:
    build: ./app3
    environment:
      - PORT=5000
    expose:
      - "5000"
    networks:
      - webnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  webnet:
    driver: bridge